apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
#      serviceAccountName: {{ .Values.appName }}
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.ImageNameTag }}
        resources:
          requests:
            memory: {{ .Values.MemoryRequest }}
            cpu: {{ .Values.CPURequest }}
          limits:
            memory: {{ .Values.MemoryLimit }}
            cpu: {{ .Values.CPULimit }}
        ports:
        - containerPort: {{ .Values.Port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}-configmap
        - secretRef:
            name: {{ .Values.appName }}-secret
        - secretRef:
            name: general-secret