apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: {{ .Values.Port }}
    targetPort: {{ .Values.targetPort }}